Repository arduino/avrdude-packing, pull requests merged in 2022-06, with the labels that each got.

#8 Correct patch for ATtiny85 erase and flash delay config adjustments
  patches/0003-Attiny85-increase-delay.patch
Labels: bug

#12 add the arduino version to the avrdude binary
  .github/workflows/release.yml
  patches/0008-Append-arduino-to-version-string.patch
Labels: type: enhancement, topic: infrastructure

#14 Remove superfluous container authorization from release workflow
  .github/workflows/release.yml
Labels: type: enhancement, topic: code
